GamesWorkShop/Controllers/CartController.cs
using GamesWorkshop.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GamesWorkshop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }
        public async Task<IActionResult> Detail()
        {
            var response = await _cartService.GetItems(User.Identity.Name);
            if (response.StatusCode == Domain.Enums.StatusCode.OK)
            {
                return View(response.Data.ToList());
            }

            return RedirectToAction("Index", controllerName: "Product");
        }
    }
}

GamesWorkShop/Controllers/ContactController.cs
using GamesWorkshop.Domain.View.ContactModels;
using GamesWorkshop.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GamesWorkshop.Controllers
{
	public class ContactController : Controller
	{
		private readonly IContactService _contactService;
		public ContactController(IContactService contactService)
		{
			_contactService = contactService;
		}
		[HttpGet]
		public IActionResult GetContact() => View();

		[HttpPost]
		public async Task<IActionResult> GetContact(CreateContactViewModel vm)
		{
			if (ModelState.IsValid)
			{
				var response = await _contactService.CreateContact(vm);
				if (response.StatusCode == Domain.Enums.StatusCode.OK)
				{
					return Json(new { description = response.Description });
				}
			}
			return StatusCode(StatusCodes.Status500InternalServerError);
		}

		[HttpGet]
		public IActionResult GetSupport() => View();
	}
}

GamesWorkShop/Controllers/UserAccountController.cs
using GamesWorkshop.Domain.Entities;
using GamesWorkshop.Domain.View.ProfileModels;
using GamesWorkshop.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GamesWorkshop.Controllers
{
    [Authorize]
    public class UserAccountController : Controller
    {
        private readonly IUserAccountService _userAccountProfleService;
        private readonly UserManager<User> _userManager;
        public UserAccountController(IUserAccountService userAccountProfleService, UserManager<User> userManager)
        {
            _userAccountProfleService = userAccountProfleService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Detail()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var response = await _userAccountProfleService.GetProfile(userId, userEmail);
            if (response.StatusCode == Domain.Enums.StatusCode.OK)
            {
                return View(response.Data);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(UserAccountViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var response = await _userAccountProfleService.Save(vm);
                if (response.StatusCode == Domain.Enums.StatusCode.OK)
                    return Json(new { description = response.Description });
            }
            //await _userAccountProfleService.Save(vm);
            var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();
            return StatusCode(StatusCodes.Status500InternalServerError);
        }

        [HttpGet]
        public async Task<IActionResult> ChangePasswordDetail()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var response = await _userAccountProfleService.GetLogin(userEmail);
            if (response != null)
                return View(response.Data);
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ChangePasswordDetail(UserLoginInfoViewModel vm)
        {
            if (!ModelState.IsValid)
                return View(vm);
            if (ModelState.IsValid)
            {
                var userEmail = User.FindFirstValue(ClaimTypes.Email);
                var result = await _userAccountProfleService.ChangePasswordAsync(vm, userEmail);
                if (result.StatusCode == Domain.Enums.StatusCode.OK)
                {
                    return Json(new { description = result.Description });
                }
            }
            return RedirectToAction(nameof(ChangePasswordDetail));
        }
    }
}

GamesWorkShop/Views/Shared/BannerPartial.cshtml
<div class="banner-top">
	<div class="container">
		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="logo">
					<h1>
						<a asp-controller="Product" asp-action="Index">
							Games Workshop
						</a>
					</h1>
				</div>
			</div>
			<!--/.navbar-header-->

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a asp-controller="Product" asp-action="Index">Home</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
						<ul class="dropdown-menu multi-column columns-2">
							<div class="row">
								<div class="col-sm-6">
									<ul class="multi-column-dropdown">
										<h6>NEW IN</h6>
										<li><a href="products.html">Warhammer Bestsellers</a></li>
										<li><a href="products.html">Warhammer 40000</a></li>
										<li><a href="products.html">Warhammer The Horus Heresy</a></li>
									</ul>
								</div>
								<div class="col-sm-6">
									<ul class="multi-column-dropdown">
										<h6>CATEGORIES</h6>
										<li><a asp-controller="Product" asp-action="GetProductsByCategory" asp-route-category="0">Space Marines</a></li>
										<li><a asp-controller="Product" asp-action="GetProductsByCategory" asp-route-category="1">Armies Of The Imperium</a></li>
										<li><a asp-controller="Product" asp-action="GetProductsByCategory" asp-route-category="2">Armies of Chaos</a></li>
										<li><a asp-controller="Product" asp-action="GetProductsByCategory" asp-route-category="3">Xenos Armies</a></li>
										<li><a asp-controller="Product" asp-action="GetProductsByCategory" asp-route-category="4">Terrain</a></li>
										<li><a asp-controller="Product" asp-action="GetProductsByCategory" asp-route-category="5">Ways to play</a></li>
									</ul>
								</div>
								<div class="clearfix"></div>
							</div>
						</ul>
					</li>
					@if (User.IsInRole("Admin"))
					{
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
							<ul class="dropdown-menu multi-column columns-2">
								<div class="row">
									<div class="col-sm-6">
										<ul class="multi-column-dropdown">
											<h6>Products</h6>
											<li><a asp-controller="Admin" asp-action="EditProducts">Edit products</a></li>
										</ul>
									</div>
									<div class="col-sm-6">
										<ul class="multi-column-dropdown">
											<h6>Users</h6>
											<li><a asp-controller="Admin" asp-action="EditUsers">User management</a></li>
										</ul>
									</div>
								</div>
							</ul>
							<div class="clearfix"></div>
						</li>
					}
					@if (User.IsInRole("Support"))
					{
						<li><a asp-controller="Contact" asp-action="GetSupport">SUPPORT</a></li>
					}
					<li><a asp-controller="Contact" asp-action="GetContact">CONTACT</a></li>
				</ul>
			</div>
			<!--/.navbar-collapse-->
		</nav>
		<!--/.navbar-->
	</div>
</div>

GamesWorkShop/Views/Shared/FooterPartial.cshtml
<div class="footer">
	<div class="container">
		<div class="footer_top">
			<div class="span_of_4">
				<div class="col-md-3 span1_of_4">
					<h4>support</h4>
					<ul class="f_nav">
						<li><a href="#">Find your store</a></li>
						<li><a href="#">Contact us</a></li>
						<li><a href="#">Delivery</a></li>
						<li><a href="#">Returns</a></li>
						<li><a href="#">Shopping FAQs</a></li>
					</ul>
				</div>
				<div class="col-md-3 span1_of_4">
					<h4>account</h4>
					<ul class="f_nav">
						<li><a href="account.html">login</a></li>
						<li><a href="register.html">create an account</a></li>
						<li><a href="#">create wishlist</a></li>
						<li><a href="checkout.html">my shopping bag</a></li>
						<li><a href="#">brands</a></li>
						<li><a href="#">create wishlist</a></li>
					</ul>
				</div>
				<div class="col-md-3 span1_of_4">
					<h4>warhammer games</h4>
					<ul class="f_nav">
						<li><a href="https://www.warhammer.com/en-FI/Warhammer-40-000-Footer">Warhammer 40,000</a></li>
						<li><a href="https://www.warhammer.com/en-FI/Warhammer-Age-of-Sigmar">Warhammer Age of Sigmar</a></li>
						<li><a href="https://www.warhammer.com/en-FI/The-Horus-Heresy">Warhammer The Horus Heresy</a></li>
						<li><a href="https://www.warhammer.com/en-FI/Middle-earth-Footer">Middle-earth Strategy Battle Game</a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="cards text-center">
			<img src="~/images/cards.jpg" alt="" />
		</div>
		<div class="copyright text-center">
			<p>© 2023 GamesWorkshop. All Rights Reserved</p>
		</div>
	</div>
</div>

GamesWorkShop/Views/Shared/HeadPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - GamesWorkShop</title>

<!-- CSS -->
<link href="~/css/bootstrap.css" rel="stylesheet" asp-append-version="true" type="text/css" />
<link href="~/css/style.css" rel="stylesheet" asp-append-version="true" type="text/css" media="all" />
<link rel="stylesheet" href="~/css/flexslider.css" asp-append-version="true" type="text/css" media="screen" />

<!-- JavaScript -->
<script src="~/js/jquery.min.js" asp-append-version="true"></script>
<script src="~/js/bootstrap-3.1.1.min.js" asp-append-version="true"></script>
<script src="~/js/simpleCart.min.js" asp-append-version="true"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="sweetalert2.all.min.js"></script>

GamesWorkShop/Views/Shared/HeaderPartial.cshtml
<div class="header">
    <div class="header-top-strip">
        <div class="container">
            @if (!User.Identity.IsAuthenticated)
            {
                <div class="header-top-left">
                    <ul>
                        <li><a asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path"><img style="width:23px;height:23px;margin-right:6px;" src="~/images/Warhammer.svg" /> Login</a></li>
                        <li><a asp-controller="Account" asp-action="Registration"><span class="glyphicon glyphicon-lock"> </span>Create an Account</a></li>
                    </ul>
                </div>
            }
            @if (User.Identity.IsAuthenticated)
            {
                <div class="header-top-left">
                    <ul>
                        <li><a asp-controller="UserAccount" asp-action="Detail"><span class="glyphicon glyphicon-user"> </span>Account</a></li>
                        <li><a asp-controller="Account" asp-route-returnUrl="@Context.Request.Path" asp-action="Logout"><span class="glyphicon glyphicon-lock"> </span>Logout</a></li>

                        <li>
                            <div class="header-right">
                                <div class="cart box_1">
                                    <a asp-controller="Cart" asp-action="Detail">
                                        <img asp-controller="Cart" asp-action="Detail" src="~/images/bag.png" alt="">
                                    </a>
                                    <div class="clearfix"> </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            }
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

GamesWorkShop/Views/Shared/NewsLetterPartial.cshtml
		<div class="news-letter">
			<div class="container">
				<div class="join">
					<h6>JOIN OUR MAILING LIST</h6>
					<div class="sub-left-right">
						<form>
							<input type="text" value="Enter Your Email Here" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email Here';}" />
							<input type="submit" value="SUBSCRIBE" />
						</form>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
		</div>

GamesWorkShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	@await Html.PartialAsync("HeadPartial")
</head>
<body>
	<header>
		@{
			await Html.RenderPartialAsync("HeaderPartial");
		}
	</header>
	@await Html.PartialAsync("BannerPartial");
	<div>
		<main role="main">
			@RenderBody()
		</main>
	</div>
	@await Html.PartialAsync("NewsLetterPartial");
	<footer>
		@await Html.PartialAsync("FooterPartial");
	</footer>
	@await RenderSectionAsync("pageScripts", false);
</body>
</html>